### ISSUE TITLE
Adicionar README.md no projeto

### ISSUE THREAD

**Issue by matheusmaximianomv** [matheusmaximianomv/desafio03-github-blog#1]
**Como padrão em projetos** o arquivo README.md serve para descrever a aplicação encontrada no repositório apresentando conceitos, fluxos de utilização, uma própria do documentação.

_Com o markdown, que_ é a extensão do arquivo, podemos criar títulos, listas, tabelas, adicionar imagens, trechos de códigos e muito mais. Tudo isso para facilitar o entendimento para terceiros e deixar mais fácil de organizar explicações em seus textos.

Exemplos:

### Content, Items e Self

- Content → justify-content e align-content, nos permite alinhar o próprio grid, relativo ao espaço fora do grid, ou seja, alinhar o grid referente ao tamanho do seu elemeto pai;
    - O uso dessas propriedades são raras, pois só é aplicado caso o grid seja menor que a área definida. (Por exemplo, quando usamos px o tamanho da grid, poderemos terminar com o tamanho da grid pequeno, para o tamanho da área do grid);
    - Valores:
        1. start;
        2. end;
        3. center;
        4. stretch;
        5. space-between;
        6. space-around;
        7. space-evenly;

```css
* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}

body {
    background: rgb(241, 62, 62);
}

section.container {
    height: 100vh;

    display: grid;
    grid-template-columns: 3fr 1fr;
    grid-template-rows: 20vh 70vh 10vh;
    grid-template-areas: 
        "header header"
        "main aside"
        "footer footer"
        ;

    /*
    Equivalentes (Espaçamentos entre linhas e coluna):
        grid-gap: 20px;
        grid-gap: 20px 20px;
        grid-row-gap: 20px;
        grid-column-gap: 20px;
    */
}
```

```typescript
const name = "Matheus Maximiano"
const age = 24;

function concatNameAge(username: string, userage: number): string {
  return `Meu nome é ${username} e eu tenho ${userage} anos.`
}

console.log(concatNameAge(name, age));
```
```go
package main

import "fmt"

func factorial(n int) int {
    if n <= 1 {
        return 1
    }
    return n * factorial(n-1)
}

func main() {
    num := 5 // O número para o qual você deseja calcular o fatorial
    result := factorial(num)
    fmt.Printf("O fatorial de %d é %d\n", num, result)
}

```
